name: Cancel superseded Hanzi release

on:
  push:
    paths:
      - .github/workflows/cancel_superseded_hanzi_release.yml

permissions:
  actions: write
  contents: read

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel old run
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh api --method POST repos/Persie0/firebase_tester_builder/actions/runs/35547714483/cancel || true
